services:
  estudiantes-service:
    build:
      context: ./Estudiante
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - app-network

  evaluacion-service:
    build:
      context: ./Evaluacion
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: desafio_db
      MYSQL_ROOT_PASSWORD: password  # <- esta es la clave para el error
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
